replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: zeppelin.127.0.0.1.nip.io
      paths:
        - /

serviceAccount:
  create: true

image:
  repository: apache/zeppelin
  tag: 0.11.2
  pullPolicy: IfNotPresent

env:
  SERVICE_DOMAIN: "zeppelin.127.0.0.1.nip.io"
  ZEPPELIN_K8S_SPARK_CONTAINER_IMAGE: gcr.io/spark-operator/spark:v3.1.1
  ZEPPELIN_K8S_CONTAINER_IMAGE: apache/zeppelin:0.11.2
  ZEPPELIN_HOME: /opt/zeppelin
  ZEPPELIN_PORT: 8080
  ZEPPELIN_SERVER_RPC_PORTRANGE: 12320:12320
  FLINK_HOME: /opt/flink
  SPARK_MASTER: k8s://https://kubernetes.default.svc
  SPARK_HOME: /spark

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

configMap:
  enabled: true
  data:
#   ZEPPELIN_NOTEBOOK_DIR: /notebooks
    ZEPPELIN_PORT: "8080"
#   ZEPPELIN_LOG_DIR: /logs

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}





