replicaCount: 1

image:
  repository: apache/zeppelin
  tag: 0.11.2
  pullPolicy: IfNotPresent

interpreter:
  image:
    repository: bitnami/spark
    tag: 4.0.0-debian-12-r2
  init:
    - name: spark
      properties:
        master: spark://spark-master-svc.spark-technical-test-data-platform.svc.cluster.local:7077
        spark.submit.deployMode: cluster
        spark.app.name: Zeppelin
        spark.executor.memory: 1g
        spark.executor.cores: 1
        SPARK_HOME: /opt/bitnami/spark
        PYSPARK_PYTHON: python3
        PYSPARK_DRIVER_PYTHON: python3

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: zeppelin.{minikube-ip}.nip.io
      paths:
        - /

serviceAccount:
  create: true
  name: zeppelin-serviceaccount

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4040"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

autoscaling:
  enabled: false

persistence:
  enabled: false

configMap:
  enabled: true
  data:
    SPARK_HOME: "/opt/bitnami/spark"
    ZEPPELIN_SPARK_CONF_DIR: "/opt/bitnami/spark/conf"
    PYSPARK_PYTHON: "python3"
    PYSPARK_DRIVER_PYTHON: "python3"

extraVolumes:
  - name: spark-share
    emptyDir: {}

extraVolumeMounts:
  - name: spark-share
    mountPath: /opt/bitnami/spark

initContainers:
  - name: spark-client-init
    image: bitnami/spark:4.0.0-debian-12-r2
    command: ["/bin/sh", "-c"]
    args:
      - cp -r /opt/bitnami/spark/* /opt/bitnami/spark/
    volumeMounts:
      - name: spark-share
        mountPath: /opt/bitnami/spark

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 240
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
