ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: zeppelin.127.0.0.1.nip.io
      paths:
        - /

serviceAccount:
  create: true

image:
  repository: apache/zeppelin
  tag: 0.12.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

configMap:
  enabled: true
  data:
    ZEPPELIN_NOTEBOOK_DIR: /notebooks
    ZEPPELIN_PORT: "8080"
    ZEPPELIN_LOG_DIR: /logs

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}





