# ... [CONTEÚDO ORIGINAL MANTIDO] ...

worker:
  enabled: true
  replicaCount: 2  # <--- CORREÇÃO APLICADA: mais de 1 worker
  # ... [demais configurações inalteradas] ...
  initContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  # ... [demais configurações inalteradas] ...

master:
  enabled: true
  replicaCount: 1
  extraContainerPorts:
    - name: driver
      containerPort: 4040
      protocol: TCP  # <--- CORREÇÃO APLICADA: driver port
  extraEnvVars:
    - name: SPARK_DRIVER_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.podIP  # <--- CORREÇÃO APLICADA: expose IP
  initContainers: []
  extraVolumes: []
  extraVolumeMounts: []

service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
    cluster: 7077
  extraPorts:
    - name: driver
      port: 4040
      targetPort: 4040
      protocol: TCP  # <--- CORREÇÃO APLICADA
  headless:
    enabled: true    # <--- CORREÇÃO APLICADA


