# Configuração da Imagem (DEVE ser igual à usada no Zeppelin)
image:
  repository: bitnami/spark
  tag: 4.0.0-debian-12-r2
  pullPolicy: IfNotPresent

# Configuração do Master (Crítico para o Zeppelin conectar)
master:
  component: spark-master
  service:
    type: ClusterIP
    ports:
      spark: 7077  # Porta principal do cluster
      webui: 8080  # UI do Spark
      driver: 4040  # Porta do driver (usada pelo Zeppelin)
    headless:
      enabled: true  # DNS discovery para workers

# Configuração dos Workers
worker:
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"

# Expor métricas e serviços adicionais
metrics:
  enabled: true
  serviceMonitor:
    enabled: false

# Permissões de Serviço (Necessário para o Zeppelin)
serviceAccount:
  create: true
  name: spark-serviceaccount

rbac:
  create: true

# Variáveis de Ambiente Específicas
extraEnvVars:
  - name: SPARK_DRIVER_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: SPARK_LOCAL_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

# Configuração de Rede Adicional
networkPolicy:
  enabled: true
  allowExternal: true  # Permite conexão do Zeppelin



