image:
  repository: bitnami/spark
  tag: 4.0.0-debian-12-r2
  pullPolicy: IfNotPresent

master:
  component: spark-master
  service:
    type: ClusterIP
    ports:
      spark: 7077
      webui: 8080
      driver: 4040
    headless:
      enabled: true

worker:
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

serviceAccount:
  create: true
  name: spark-serviceaccount

rbac:
  create: true

extraEnvVars:
  - name: SPARK_DRIVER_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: SPARK_LOCAL_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

networkPolicy:
  enabled: true
  allowExternal: true



