ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: zeppelin.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
serviceAccount:
  create: true
